---
name: default
on: push
stages:
  - build
  - deploy

build-job:

  stage: build
  
  script:
       echo "build"

deploy-job:

  stage: deploy
  
  script:
     echo "Testing complete"         
---
