on: push
jobs:
  my-job1:
    runs-on: windows-latest
    steps:
      - name: Install Dependencies
        run: |
             curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
             python get-pip.py
