on: push
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Poetry run
        run: |
          curl -sSL https://install.python-poetry.org | python -
          poetry update
        shell: bash
