on: push
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Install
        uses: actions/upload-artifact@v3
        with:
          name: homework
          path: mkdocs.yml
  job2:
    runs-on: windows-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: homework
