on: push
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Poetry run
        run: |
          $ poetry install
          $ poetry update
          $ poetry run mkdocs build --config-file mkdocs.yml
        shell: bash
