on: push
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Poetry run
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -oget-pip.py
          python get-pip.py
          pip install mkdocs
          poetry run mkdocs build --config-file mkdocs.yml
