---
stages:
  - build
  - deploy

build-job:

  stage: build
  
  script:
      - echo "build"
      - echo "Testing"

      
Pages:

  stage: deploy
  
  script:
    - move usermanual_site
    - echo "Testing complete"
    
  artifacts:
    paths:
      - usermanual_site/
            
---
