on: push
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: 'homework'
          path: https://github.com/ShivprasadKolekar/Main/blob/main/mkdocs.yml
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: 'homework'
          path: some/new/dir1
      - name: Install
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -0 get-pip.py
          python get-pip.py
          pip install mkdocs
          cd dir1
          mkdocs build
