on: push
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Pip mkdocs run
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python get-pip.py
          pip install mkdocs
          shell: bash
