---
stages:
  - build
  - deploy

build-job:

  stage: build
  
  script:
      - echo "build"
      - echo "Testing"

      
deploy-job:

  stage: deploy
  
  script:
    - echo "Testing complete"
    
            
---
